import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    welcome_back: 'Welcome back',
    login_subtitle: 'Select your portal to continue',
    login_as: 'Log in as',
    email: 'Email',
    password: 'Password',
    forgot_password: 'Forgot password?',
    logging_in: 'Logging in...',
    log_in: 'Log in',
    no_account: "Don't have an account?",
    create_one: 'Create one',
    or: 'or',
    continue_with_google: 'Continue with Google',
    portal_admin: 'Organisation Admin',
    portal_admin_desc: 'Manage programmes & users',
    portal_reviewer: 'Reviewer',
    portal_reviewer_desc: 'Evaluate applications',
    portal_donor: 'Donor',
    portal_donor_desc: 'Track portfolio & impact',
    portal_applicant: 'Applicant',
    portal_applicant_desc: 'Apply for programmes',
    dashboard: 'Dashboard',
    programmes: 'Programmes',
    applications: 'Applications',
    users: 'Users',
    grants: 'Grants',
    analytics: 'Analytics',
    messages: 'Messages',
    notifications: 'Notifications',
    settings: 'Settings',
    logout: 'Logout',
    search: 'Search programmes, applications...',
    welcome: 'Welcome',
    new_programme: 'New Programme',
    active_programmes: 'Active Programmes',
    pending_applications: 'Pending Applications',
    total_budget: 'Total Budget',
    disbursed: 'Disbursed',
    recent_applications: 'Recent Applications',
    quick_actions: 'Quick Actions',
    type_message: 'Type a message...',
    select_contact: 'Select a contact to start messaging',
    all_programmes: 'All Programmes',
  },
  fr: {
    welcome_back: 'Bienvenue',
    login_subtitle: 'Sélectionnez votre portail pour continuer',
    login_as: 'Se connecter en tant que',
    email: 'E-mail',
    password: 'Mot de passe',
    forgot_password: 'Mot de passe oublié?',
    logging_in: 'Connexion en cours...',
    log_in: 'Se connecter',
    no_account: 'Pas de compte?',
    create_one: 'Créer un',
    or: 'ou',
    continue_with_google: 'Continuer avec Google',
    portal_admin: 'Admin Organisation',
    portal_admin_desc: 'Gérer les programmes et utilisateurs',
    portal_reviewer: 'Évaluateur',
    portal_reviewer_desc: 'Évaluer les candidatures',
    portal_donor: 'Donateur',
    portal_donor_desc: 'Suivre le portefeuille et l\'impact',
    portal_applicant: 'Candidat',
    portal_applicant_desc: 'Postuler aux programmes',
    dashboard: 'Tableau de bord',
    programmes: 'Programmes',
    applications: 'Candidatures',
    users: 'Utilisateurs',
    grants: 'Subventions',
    analytics: 'Analytique',
    messages: 'Messages',
    notifications: 'Notifications',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    search: 'Rechercher des programmes, candidatures...',
    welcome: 'Bienvenue',
    new_programme: 'Nouveau Programme',
    active_programmes: 'Programmes Actifs',
    pending_applications: 'Candidatures en Attente',
    total_budget: 'Budget Total',
    disbursed: 'Décaissé',
    recent_applications: 'Candidatures Récentes',
    quick_actions: 'Actions Rapides',
    type_message: 'Tapez un message...',
    select_contact: 'Sélectionnez un contact pour commencer',
    all_programmes: 'Tous les Programmes',
  },
  sw: {
    welcome_back: 'Karibu tena',
    login_subtitle: 'Chagua lango lako kuendelea',
    login_as: 'Ingia kama',
    email: 'Barua pepe',
    password: 'Nywila',
    forgot_password: 'Umesahau nywila?',
    logging_in: 'Inaingia...',
    log_in: 'Ingia',
    no_account: 'Huna akaunti?',
    create_one: 'Unda moja',
    or: 'au',
    continue_with_google: 'Endelea na Google',
    portal_admin: 'Admin wa Shirika',
    portal_admin_desc: 'Simamia programu na watumiaji',
    portal_reviewer: 'Mkaguzi',
    portal_reviewer_desc: 'Kagua maombi',
    portal_donor: 'Mfadhili',
    portal_donor_desc: 'Fuatilia kwingineko na athari',
    portal_applicant: 'Mwombaji',
    portal_applicant_desc: 'Omba programu',
    dashboard: 'Dashibodi',
    programmes: 'Programu',
    applications: 'Maombi',
    users: 'Watumiaji',
    grants: 'Ruzuku',
    analytics: 'Uchanganuzi',
    messages: 'Ujumbe',
    notifications: 'Arifa',
    settings: 'Mipangilio',
    logout: 'Toka',
    search: 'Tafuta programu, maombi...',
    welcome: 'Karibu',
    new_programme: 'Programu Mpya',
    active_programmes: 'Programu Zinazoendelea',
    pending_applications: 'Maombi Yanayosubiri',
    total_budget: 'Bajeti Jumla',
    disbursed: 'Imetolewa',
    recent_applications: 'Maombi ya Hivi Karibuni',
    quick_actions: 'Vitendo vya Haraka',
    type_message: 'Andika ujumbe...',
    select_contact: 'Chagua mwasiliano kuanza',
    all_programmes: 'Programu Zote',
  },
  pt: {
    welcome_back: 'Bem-vindo de volta',
    login_subtitle: 'Selecione o seu portal para continuar',
    login_as: 'Entrar como',
    email: 'E-mail',
    password: 'Senha',
    forgot_password: 'Esqueceu a senha?',
    logging_in: 'Entrando...',
    log_in: 'Entrar',
    no_account: 'Não tem conta?',
    create_one: 'Criar uma',
    or: 'ou',
    continue_with_google: 'Continuar com Google',
    portal_admin: 'Admin da Organização',
    portal_admin_desc: 'Gerir programas e utilizadores',
    portal_reviewer: 'Revisor',
    portal_reviewer_desc: 'Avaliar candidaturas',
    portal_donor: 'Doador',
    portal_donor_desc: 'Acompanhar portfólio e impacto',
    portal_applicant: 'Candidato',
    portal_applicant_desc: 'Candidatar-se a programas',
    dashboard: 'Painel',
    programmes: 'Programas',
    applications: 'Candidaturas',
    users: 'Utilizadores',
    grants: 'Subsídios',
    analytics: 'Análises',
    messages: 'Mensagens',
    notifications: 'Notificações',
    settings: 'Configurações',
    logout: 'Sair',
    search: 'Pesquisar programas, candidaturas...',
    welcome: 'Bem-vindo',
    new_programme: 'Novo Programa',
    active_programmes: 'Programas Ativos',
    pending_applications: 'Candidaturas Pendentes',
    total_budget: 'Orçamento Total',
    disbursed: 'Desembolsado',
    recent_applications: 'Candidaturas Recentes',
    quick_actions: 'Ações Rápidas',
    type_message: 'Escreva uma mensagem...',
    select_contact: 'Selecione um contato para começar',
    all_programmes: 'Todos os Programas',
  },
  ar: {
    welcome_back: 'مرحباً بعودتك',
    login_subtitle: 'اختر بوابتك للمتابعة',
    login_as: 'تسجيل الدخول كـ',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    forgot_password: 'نسيت كلمة المرور؟',
    logging_in: 'جارٍ تسجيل الدخول...',
    log_in: 'تسجيل الدخول',
    no_account: 'ليس لديك حساب؟',
    create_one: 'أنشئ واحدًا',
    or: 'أو',
    continue_with_google: 'المتابعة مع Google',
    portal_admin: 'مدير المنظمة',
    portal_admin_desc: 'إدارة البرامج والمستخدمين',
    portal_reviewer: 'المراجع',
    portal_reviewer_desc: 'تقييم الطلبات',
    portal_donor: 'المانح',
    portal_donor_desc: 'تتبع المحفظة والأثر',
    portal_applicant: 'مقدم الطلب',
    portal_applicant_desc: 'التقدم للبرامج',
    dashboard: 'لوحة التحكم',
    programmes: 'البرامج',
    applications: 'الطلبات',
    users: 'المستخدمون',
    grants: 'المنح',
    analytics: 'التحليلات',
    messages: 'الرسائل',
    notifications: 'الإشعارات',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    search: 'ابحث عن برامج، طلبات...',
    welcome: 'أهلاً',
    new_programme: 'برنامج جديد',
    active_programmes: 'البرامج النشطة',
    pending_applications: 'الطلبات المعلقة',
    total_budget: 'الميزانية الإجمالية',
    disbursed: 'تم الصرف',
    recent_applications: 'الطلبات الأخيرة',
    quick_actions: 'إجراءات سريعة',
    type_message: 'اكتب رسالة...',
    select_contact: 'اختر جهة اتصال للبدء',
    all_programmes: 'جميع البرامج',
  },
};

const LanguageContext = createContext({ lang: 'en', t: (k) => k, setLang: () => {} });

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('nx_lang') || 'en');
  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;
  const changeLang = (l) => { setLang(l); localStorage.setItem('nx_lang', l); };
  return (
    <LanguageContext.Provider value={{ lang, t, setLang: changeLang }}>
      <div dir={lang === 'ar' ? 'rtl' : 'ltr'}>{children}</div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export const LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'sw', label: 'Kiswahili', flag: '🇰🇪' },
  { code: 'pt', label: 'Português', flag: '🇧🇷' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦' },
];